# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-19 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('urls_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Alive'), ('BROKEN', 'Broken'), ('LIVENESS_CHECK_FAILED', 'Liveness Check Failed')], max_length=64)),
                ('documents', models.ManyToManyField(to='core.Document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='links',
            field=models.ManyToManyField(to='core.Link'),
        ),
    ]
