# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-20 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='documents',
        ),
        migrations.AlterField(
            model_name='document',
            name='links',
            field=models.ManyToManyField(related_name='documents', to='core.Link'),
        ),
    ]
